---
title: "load-data"
author: "Grayson White"
date: "10/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```

## Loading the GSS dataset

```{r eval = FALSE}
# pull gss data
temp <- tempfile()
download.file("https://gss.norc.org/documents/stata/GSS_stata.zip",temp)

# if this next line errors with "No such file or directory", try
# incrementing the number after "_R"
gss_orig <- haven::read_dta(unz(temp, filename = "GSS7218_R3.DTA")) %>%
  haven::as_factor()
unlink(temp)

save(gss_orig, file = "gss_orig.rda")
```

## Filtering

```{r}
load("gss_orig.rda")


# Much of this script is from the {infer} package subsetting of the gss dataset
gss_subset <- gss_orig %>%
  filter(!stringr::str_detect(sample, "blk oversamp")) %>% # this is for weighting
  select(year, age, sex, college = degree, partyid, hompop, 
         hours = hrs1, income, class, finrela, weight = wtssall) %>%
  mutate_if(is.factor, ~fct_collapse(., NULL = c("IAP", "NA", "iap", "na"))) %>%
  mutate(age = age %>%
           fct_recode("89" = "89 or older",
                      NULL = "DK") %>% # truncated at 89
           as.character() %>%
           as.numeric(),
         hompop = hompop %>%
           fct_collapse(NULL = c("DK")) %>%
           as.character() %>%
           as.numeric(),
         hours = hours %>%
           fct_recode("89" = "89+ hrs",
                      NULL = "DK") %>% # truncated at 89
           as.character() %>%
           as.numeric(),
         weight = weight %>%
           as.character() %>%
           as.numeric(),
         partyid = fct_collapse(partyid, 
           dem = c("strong democrat", "not str democrat"),
           rep = c("strong republican", "not str republican"),
           ind = c("ind,near dem", "independent", "ind,near rep"),
           other = "other party"
         ),
         income = factor(income, ordered = TRUE),
         college = fct_collapse(college,
           degree = c("junior college", "bachelor", "graduate"),
           "no degree"  = c("lt high school", "high school"),
           NULL = "dk" # no dks show up in the data, so drop this level
         )
         ) %>%
  filter(year >= 2000) %>%
  filter(partyid %in% c("dem", "rep")) %>%
  drop_na()

# save(gss_subset, file = "gss_subset.rda")
```


